Updated CI build

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -20,18 +20,31 @@ jobs:
         ansible: [2.16.0]
     steps:
       - name: Check out code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up Python 3.12
-        uses: actions/setup-python@v1
+        uses: actions/setup-python@v5
         with:
           python-version: 3.12
+          cache: pip
 
-      - name: Get Python and Pip version
-        run: echo $(pip --version)
+      - name: Configure pip retries
+        run: |
+          mkdir -p ~/.config/pip
+          cat > ~/.config/pip/pip.conf <<EOF
+          [global]
+          timeout = 120
+          retries = 10
+          disable-pip-version-check = true
+          EOF
+
+      - name: Show Python and pip versions
+        run: |
+          python --version
+          pip --version
 
       - name: Install ansible-base (v${{ matrix.ansible }})
-        run: pip install https://github.com/ansible/ansible/archive/v${{ matrix.ansible }}.tar.gz --disable-pip-version-check
+        run: pip install https://github.com/ansible/ansible/archive/v${{ matrix.ansible }}.tar.gz
 
       - name: Build a collection tarball
         run: ansible-galaxy collection build
@@ -40,26 +53,23 @@ jobs:
         run: ansible-galaxy collection install *.tar.gz
 
       - name: Run unit tests
-        run: ansible-test units --docker -v --color --truncate 0 --python 3.12
         working-directory: ${{ env.HOME }}/.ansible/collections/ansible_collections/vmware/alb
+        run: |
+          for i in 1 2 3; do
+            echo "Unit test attempt $i..."
+            ansible-test units --docker -v --color --truncate 0 --python 3.12 && exit 0
+            echo "Attempt $i failed. Retrying in 20 seconds..."
+            sleep 20
+          done
+          exit 1
 
-      - name: Run ansible sanity tests
-        run: ansible-test sanity --docker -v --color --truncate 0 --python 3.12
+      - name: Run sanity tests
         working-directory: ${{ env.HOME }}/.ansible/collections/ansible_collections/vmware/alb
-
-      # Always install galaxy-importer after the unit tests are finished as it is overriding the existing
-      # ansible installation. Ref: https://github.com/ansible/ansible/issues/76361
-      # - name: Install galaxy-importer
-      #   run: ANSIBLE_SKIP_CONFLICT_CHECK=${{ env.ANSIBLE_SKIP_CONFLICT_CHECK }} pip install galaxy-importer
-
-      # - name: Create galaxy-importer directory
-      #   run: sudo mkdir -p /etc/galaxy-importer
-
-      # - name: Create galaxy-importer.cfg
-      #   run: sudo cp ${{ env.HOME }}/.ansible/collections/ansible_collections/vmware/alb/.github/workflows/galaxy-importer.cfg /etc/galaxy-importer/galaxy-importer.cfg
-
-      # - name: Run galaxy-importer check
-      #   run: python -m galaxy_importer.main ${GITHUB_WORKSPACE}/vmware-*.tar.gz | tee ${GITHUB_WORKSPACE}/log.txt
-
-      # - name: Check errors
-      #   run: if grep -E 'ERROR' ${GITHUB_WORKSPACE}/log.txt; then exit 1; else exit 0; fi
+        run: |
+          for i in 1 2 3; do
+            echo "Sanity test attempt $i..."
+            ansible-test sanity --docker -v --color --truncate 0 --python 3.12 && exit 0
+            echo "Attempt $i failed. Retrying in 20 seconds..."
+            sleep 20
+          done
+          exit 1
